[project]
name = "new-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dagster>=1.13.11",
    "dagster-dbt>=0.29.11",
    "dagster-webserver>=1.13.11",
    "dbt-core==1.11.8",
    "dbt-snowflake==1.11.4",
    "python-dotenv>=1.2.2",
]
